name: Check Breaking Changes

on:
  pull_request:
    branches:
      - main

jobs:
  breaking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # PR の比較元ブランチを取得

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} || echo "No remote base branch found"

      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Check for breaking changes
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/${{ github.event.pull_request.base.ref }}; then
            buf breaking --against '.git#branch=${{ github.event.pull_request.base.ref }}'
          else
            echo "Base branch not found. Skipping buf breaking check."
          fi
