name: Check Breaking Changes

on:
  pull_request:
    branches:
      - main

jobs:
  breaking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64 -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Check for breaking changes
        run: buf breaking --against '.git#branch=main'
